name: test
on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Run linting script
      run: ${PWD}/hack/ci/link-check.sh
